name: Ejecutar JS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Ejecutar JS tests
        run: |
          for f in assets/js/test/*.test.js; do
            echo "Running $f"
            node $f
          done
